import { NgModule } from "@angular/core";
import {
  psdCalendarDirective,
  psdDropdownDirective,
  psdMenuDirective,
  psdMultiSelectDirective,
  psdTooltipDirective,
  psdAutoCompleteDirective,
  psdCascadeSelectDirective,
  psdColorPickerDirective,
  psdMegaMenuDirective,
  psdMenuBarDirective,
  psdSlideMenuDirective,
  psdTieredMenuDirective,
  psdOverlayPanelDirective,
  psdSplitButtonDirective,
  psdTreeSelectDirective,
  psdPaginatorDirective,
} from "./directives";
import { psdConfirmPopupDirective } from "./directives/confirmpopup";

@NgModule({
  declarations: [
    psdDropdownDirective,
    psdCalendarDirective,
    psdTooltipDirective,
    psdMultiSelectDirective,
    psdMenuDirective,
    psdAutoCompleteDirective,
    psdCascadeSelectDirective,
    psdColorPickerDirective,
    psdMegaMenuDirective,
    psdMenuBarDirective,
    psdConfirmPopupDirective,
    psdSlideMenuDirective,
    psdTieredMenuDirective,
    psdOverlayPanelDirective,
    psdSplitButtonDirective,
    psdTreeSelectDirective,
    psdPaginatorDirective,
  ],
  exports: [
    psdDropdownDirective,
    psdCalendarDirective,
    psdTooltipDirective,
    psdMultiSelectDirective,
    psdMenuDirective,
    psdAutoCompleteDirective,
    psdCascadeSelectDirective,
    psdColorPickerDirective,
    psdMegaMenuDirective,
    psdMenuBarDirective,
    psdConfirmPopupDirective,
    psdSlideMenuDirective,
    psdTieredMenuDirective,
    psdOverlayPanelDirective,
    psdSplitButtonDirective,
    psdTreeSelectDirective,
    psdPaginatorDirective,
  ]
})
export class PrimeNGShadowDOMDirective { }